### ISSUE TITLE
Add overlays and points of interests

### ISSUE THREAD

**Issue by WUOTE** [acidflow-noita/noitamap#5]
We want to provide functionality similar to the old [easyzoom maps'](https://easyzoom.com/image/260463).

In order to do that, we need to implement overlays, the easiest way to do this is to partially reuse the easyzoom's overlays by extracting useful info, then readjusting them to the new maps' sizes found in the `dzi` files for the maps:
https://github.com/acidflow-noita/noitamap/blob/00df67642be2ec6a1cdd6de53077da639659c450/public/js/script.js#L7

```XML
{"Image":{"xmlns":"http://schemas.microsoft.com/deepzoom/2008","Format":"webp","Overlap":"2","TileSize":"512","Size":{"Width":"51200","Height":"73728"},"TopLeft":{"X":"-25600","Y":"-31744"}}}
```

Easyzoom overlays are stored like [this](https://easyzoom.com/api/image/260463/comment).

**Comment by JeanChristopheM** [comment]
I have been looking into this but can't figure out the math to convert easyzoom's data to your map's coordinates.
Do you have any pointers to help me figure this out ? Figuring out new coordinates seems dreadful if it can be avoided for most POI

**Comment by JeanChristopheM** [comment]
Hey cheers for the quick reply. It seems I misunderstood the scope of this issue.
I thought you just wanted to add more data to the current overlayText variable and figured it was something easy enough I could contribute to.

I have [created a pull request](https://github.com/acidflow-noita/noitamap/pull/32) having my idea in mind but feel free to discard it if you want as I clearly misread your intentions.

I might look into what you actually wanted but I am afraid it looks slightly out of my knowledge.
